account/urls.py
from django.urls import path , include
from . import views
from knox import views as knox_views
app_name = 'account'

urlpatterns = [
    path('signup/', views.signup , name="signup" ),
    ################# api ############
    path('api/register/', views.RegisterAPI.as_view(), name='register'),
    path('api/login/', views.LoginAPI.as_view(), name='login'),
    path('api/logout/', knox_views.LogoutView.as_view(), name='logout'),
    path('api/logoutall/', knox_views.LogoutAllView.as_view(), name='logoutall'),
    ################# api ############
    
]

product/urls.py
from django.urls import path , include
from . import views
from rest_framework.routers import DefaultRouter
from . import api
############################
router = DefaultRouter()
router.register('', api.ProductViewSet, basename='productViewSet')
############################
app_name = 'product'

urlpatterns = [
    path('',  views.product_list , name="product_list"),
    path('<int:id>',  views.product_details , name= 'product_details' ),
    ############################
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    ############################
    path('product/api/', include(router.urls) , name='postvs'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('' , include('product.urls' , namespace= 'product')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls' , namespace= 'accounts' )),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

product/models.py
from distutils.command.upload import upload
from itertools import product
from logging import PlaceHolder
from operator import mod
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=100 , verbose_name= _("Product Name") , null=True )
    price = models.DecimalField(max_digits=5 , decimal_places=2 , verbose_name = _("price"))
    image = models.ImageField(upload_to='products/') 

    PRDSlug = models.SlugField(null=True , blank=True , verbose_name=("Product url"))
    
    def save(self, *args , **kwargs):
        if not self.PRDSlug :
            self.PRDSlug = slugify(self.name)
        super(Product , self).save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse('product:product_details', kwargs={'id': self.id})
    
    def __str__(self) :
        return self.name

account/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username' , 'first_name' , 'last_name' , 'email']

account/views.py
#from multiprocessing import context
from django.shortcuts import render , redirect 
#from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login , authenticate 
# Create your views here.
#################api###################
from rest_framework import generics , permissions
from rest_framework.response import Response
from knox.models import AuthToken
from .serilizer import UserSerializer, RegisterSerializer
from knox.views import LoginView as KnoxLoginView
from rest_framework.authtoken.serializers import AuthTokenSerializer

################api #################3

def signup(request):
    if request.method =="POST" :
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            
            user = authenticate(username = username , password = password)
            login(request , user)
            return redirect('/')
            
    else:
        form = UserCreationForm()
    
    context = {'form' : form}         #{form of templete: above form}
    return render(request , 'registration/signup.html' , context)
####################################### API ########################


# Register API
class RegisterAPI(generics.GenericAPIView):
    serializer_class = RegisterSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        return Response({
        "user": UserSerializer(user, context=self.get_serializer_context()).data,
        "token": AuthToken.objects.create(user)[1]
        })

class LoginAPI(KnoxLoginView):
    permission_classes = (permissions.AllowAny,)

    def post(self, request, format=None):
        serializer = AuthTokenSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        return super(LoginAPI, self).post(request, format=None)
####################################### API ########################

product/views.py
from django.shortcuts import redirect, render
from .models import Product 
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

######################################
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
######################################
########## filter ###########
from .filters import ProductFilter
######### filter ###########
# Create your views here.


def product_list (request):
    product_list = Product.objects.get_queryset().order_by('-price')
    
    #Filter
    filter = ProductFilter(request.GET, queryset=product_list)
    product_list = filter.qs
    #Filter

    paginator = Paginator(product_list, 2) # Show 2 contacts per page.
    page_number = request.GET.get('page')
    product_list = paginator.get_page(page_number)

    context = {'product_list' : product_list , 'filter' : filter}
    return render(request , 'product/product_list.html' , context)
    

def product_details (request , id):
    
    product_details = Product.objects.get(id=id)
    context = {'product_details' : product_details}
    return render(request , 'product/product_details.html' , context)

#########################################
@login_required(login_url="/users/login")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)    
    return redirect("product:product_list")


@login_required(login_url="/users/login")
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("product:cart_detail")


@login_required(login_url="/users/login")
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("product:cart_detail")


@login_required(login_url="/users/login")
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("product:cart_detail")


@login_required(login_url="/users/login")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("product:cart_detail")


@login_required(login_url="/users/login")
def cart_detail(request):
    return render(request, 'product/cart_detail.html')

account/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          {% if product_details.PRDImge %}
             <img src="{{profile.image}}" class="img-fluid" alt="">
          {% else %}
             <img src="{% static 'site_static/img/def_user_icon .jpg' %}" class="img-fluid" alt="">
          {% endif %}

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="">

            <div class="mb-3">

                <form class="row g-3" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-md-6">
                      <label for="inputEmail4" class="form-label">Email</label>
                      <input type="email" class="form-control" id="inputEmail4" >
                    </div>
                    <div class="col-md-6">
                      <label for="inputPassword4" class="form-label">Password</label>
                      <input type="password" class="form-control" id="inputPassword4">
                    </div>
                    <div class="col-12">
                      <label for="inputAddress" class="form-label">Address</label>
                      <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
                    </div>
                    <div class="col-12">
                      <label for="inputAddress2" class="form-label">Address 2</label>
                      <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
                    </div>
                    <div class="col-md-6">
                      <label for="inputCity" class="form-label">City</label>
                      <input type="text" class="form-control" id="inputCity">
                    </div>
                    <div class="col-md-4">
                      <label for="inputState" class="form-label">State</label>
                      <select id="inputState" class="form-select">
                        <option selected>Choose...</option>
                        <option>...</option>
                      </select>
                    </div>
                    <div class="col-md-2">
                      <label for="inputZip" class="form-label">Zip</label>
                      <input type="text" class="form-control" id="inputZip">
                    </div>
                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck">
                        <label class="form-check-label" for="gridCheck">
                          Check me out
                        </label>
                      </div>
                    </div>
                    <div class="col-12">
                      <button type="submit" class="btn btn-primary">Sign in</button>
                    </div>
                  </form>
            </div>


            <p class="lead font-weight-bold">Description</p>

      
              <a class="btn btn-primary btn-md my-0 p" type="submit">Edit My Profile
                <i class="fas fa-shopping-cart ml-1"></i>
                </a>


          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
      

      <hr>


  </main>
  <!--Main layout-->

  {% endblock body %}

account/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          {% if product_details.PRDImge %}
             <img src="{{profile.image}}" class="img-fluid" alt="">
          {% else %}
             <img src="{% static 'site_static/img/def_user_icon .jpg' %}" class="img-fluid" alt="">
          {% endif %}

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="">

            <div class="mb-3">

              {% if product_details.PRDISNew %}
                <a href="">
                  <span class="badge blue mr-1">New</span>
                </a>
              {% endif %}

              {% if product_details.PRDISBestsaller %}
                <a href="">
                  <span class="badge red mr-1">Bestseller</span>
                </a>
              {% endif %}

              {% if product_details.PRDDisccountPrice %}
                <a href="">
                  <span class="badge green mr-1">Sale</span>
                </a>
              {% endif %}

            </div>
            <p class="lead font-weight-bold">{{profile}}</p>
            <p class="lead">
              <p>{{profile.user.email}}</p>
              <p>{{profile.country}} - {{profile.PRFaddress}}</p>
              <p>{{profile.user.email}}</p>
              <p>{{profile.user.email}}</p>

            </p>

            <p class="lead font-weight-bold">Description</p>

      
              <a class="btn btn-primary btn-md my-0 p" type="submit">Edit My Profile
                <i class="fas fa-shopping-cart ml-1"></i>
                </a>


          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
      
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-10 text-center">
          <h4>My Orders</h4>

          <table class="table caption-top">
            <caption>List of users</caption>
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
              </tr>
              <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>Thornton</td>
                <td>@fat</td>
              </tr>
              <tr>
                <th scope="row">3</th>
                <td>Larry</td>
                <td>the Bird</td>
                <td>@twitter</td>
              </tr>
            </tbody>
          </table>

        </div>
      <!--Grid row-->
    </div>


  </main>
  <!--Main layout-->

  {% endblock body %}

product/templates/product/cart_detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block body %}

{% load cart_tag %}

Total Length :: {{request.session.cart|length}}

Cart Detail:

{% for key,value in request.session.cart.items %}

<p>product name :     {{value.name}} </p>
<p>product price :    {{value.price}} </p>
<p>product quantity : {{value.quantity}} </p>
<p>quantity :         {{value.image}} </p>
<p>Total {{ value.price|multiply:value.quantity }} </p>

{% endfor %}


  {% endblock body %}

product/templates/product/product_details.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block body %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          {% if product_details.PRDImge %}
             <img src="{{product_details.PRDImge.url}}" class="img-fluid" alt="">
          {% else %}
             <img src="{% static 'site_static/img/no-image.jpg' %}" class="img-fluid" alt="">
          {% endif %}

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="">

            <div class="mb-3">

            </div>
            <p class="lead font-weight-bold">{{product_details}}</p>
            <p class="lead font-weight-bold">{{product_details_id}}</p>
            <p class="lead">
              <span class="mr-1">${{product_details.price}}</span>
            </p>


              <!-- Default input -->
              
              <a href="{% url 'product:cart_add' product_details.id %}" class="btn btn-primary btn-md my-0 p" >Add to cart
                <i class="fas fa-shopping-cart ml-1"></i></a>
              
              
              <button class="btn btn-primary btn-md my-0 p" type="submit" src = "{% url 'product:cart_clear' %}" >Clear Cart</button>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->

  </main>
  <!--Main layout-->

  {% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Souq</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'site_static/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'site_static/css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'site_static/css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/" target="_blank">
        <strong class="blue-text">Souq</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> 1 </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          {% if user.is_authenticated %}
            <div class="dropdown">
              <button class="nav-link border border-light rounded waves-effect dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.get_username }}
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">My Orders</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Signout</a>

              </div>
            </div>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link border border-light rounded waves-effect">
                <i class="fa-solid fa-right-to-bracket mr-2"></i>Login
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'accounts:signup' %}" class="nav-link border border-light rounded waves-effect">
                <i class="fa-solid fa-user-plus mr-2"></i>Signup
              </a>
            </li>
          {% endif %}

        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  {% block body %}

  {% endblock body %}
  <!--Main layout-->

  
  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">



    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'site_static/js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'site_static/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'site_static/js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'site_static/js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>